server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book_collecion?serverTimezone=UTC-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /res/**
  mybatis:
    mapper-locations: classpath:mapping/*Mapping.xml
    type-aliases-package: top.xinsin.demo.mapper