server:
  port: 8080
spring:
  datasource:
    username: witstalk
    password: withTalk
    url: jdbc:mysql://wzpmc.cn:3306/witstalk?serverTimezone=UTC-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /res/**
  mybatis:
    mapper-locations: classpath:mapping/*Mapping.xml
    type-aliases-package: top.xinsin.demo.mapper